version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: wojkot/projekt:geocache
    deploy:
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
